# Generated by Django 3.2.4 on 2021-06-12 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210612_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
